// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "有梦才有远方";

const lessonData = [
    // ===== 第1段 =====
    ["雪野", "xuě yě", "snowy field", "padang salji"],
    ["茫茫", "máng máng", "vast", "luas"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["知道", "zhī dào", "know", "tahu"],
    ["一棵", "yī kē", "a", "sebatang"],
    ["小草", "xiǎo cǎo", "grass", "rumput"],
    ["的", "de", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["寒冷", "hán lěng", "cold", "sejuk"],
    ["孤寂", "gū jì", "lonely", "sunyi"],
    ["中", "zhōng", "in", "dalam"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["怀抱", "huái bào", "embrace", "memeluk"],
    ["一个", "yī gè", "a", "sebuah"],
    ["信念", "xìn niàn", "faith", "keyakinan"],
    ["取暖", "qǔ nuǎn", "keep warm", "memanaskan"],
    ["，", "", "", ""],
    ["等到", "děng dào", "wait until", "tunggu sehingga"],
    ["春归大地", "chūn guī dà dì", "spring returns to earth", "musim bunga kembali ke bumi"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["就", "jiù", "then", "lalu"],
    ["会", "huì", "will", "akan"],
    ["以", "yǐ", "with", "dengan"],
    ["两片", "liǎng piàn", "two", "dua helai"],
    ["绿叶", "lǜ yè", "green leaves", "daun hijau"],
    ["问候", "wèn hòu", "greet", "menyapa"],
    ["春天", "chūn tiān", "spring", "musim bunga"],
    ["，", "", "", ""],
    ["而", "ér", "and/while", "dan"],
    ["那", "nà", "that", "itu"],
    ["两片", "liǎng piàn", "two", "dua helai"],
    ["绿叶", "lǜ yè", "green leaves", "daun hijau"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "is exactly", "ialah"],
    ["曾经", "céng jīng", "once", "pernah"],
    ["在", "zài", "in", "di"],
    ["雪地", "xuě dì", "snow ground", "tanah salji"],
    ["下", "xià", "under", "bawah"],
    ["轻轻", "qīng qīng", "gently", "perlahan"],
    ["的", "de", "", ""],
    ["梦呓", "mèng yì", "sleep talk", "igauan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["候鸟", "hòu niǎo", "migratory bird", "burung berhijrah"],
    ["南飞", "nán fēi", "fly south", "terbang ke selatan"],
    ["，", "", "", ""],
    ["征途", "zhēng tú", "journey", "perjalanan"],
    ["迢迢", "tiáo tiáo", "far", "jauh"],
    ["。", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["的", "de", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["呢", "ne", "", ""],
    ["？", "", "", ""],
    ["在", "zài", "in", "di"],
    ["远方", "yuǎn fāng", "faraway place", "tempat jauh"],
    ["，", "", "", ""],
    ["在", "zài", "in", "di"],
    ["视野", "shì yě", "field of view", "pandangan"],
    ["里", "lǐ", "in", "dalam"],
    ["，", "", "", ""],
    ["那是", "nà shì", "that is", "itu adalah"],
    ["南方", "nán fāng", "south", "selatan"],
    ["湛蓝", "zhàn lán", "azure", "biru cerah"],
    ["的", "de", "", ""],
    ["大海", "dà hǎi", "sea", "laut"],
    ["。", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["很", "hěn", "very", "sangat"],
    ["累", "lèi", "tired", "letih"],
    ["很", "hěn", "very", "sangat"],
    ["累", "lèi", "tired", "letih"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["依然", "yī rán", "still", "masih"],
    ["往前", "wǎng qián", "forward", "ke hadapan"],
    ["奋飞", "fèn fēi", "fly vigorously", "terbang dengan gigih"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["梦", "mèng", "dream", "impian"],
    ["又", "yòu", "again", "lagi"],
    ["赐给", "cì gěi", "give", "memberi"],
    ["她", "tā", "her", "dia"],
    ["一对", "yī duì", "a pair", "sepasang"],
    ["翅膀", "chì bǎng", "wings", "sayap"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["窗前", "chuāng qián", "in front of window", "di hadapan tingkap"],
    ["托腮", "tuō sāi", "hold chin", "menyangga dagu"],
    ["的", "de", "", ""],
    ["少女", "shào nǚ", "girl", "gadis"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["是", "shì", "are", "ialah"],
    ["想", "xiǎng", "want", "mahu"],
    ["做", "zuò", "be", "menjadi"],
    ["一朵", "yī duǒ", "a", "sekuntum"],
    ["云", "yún", "cloud", "awan"],
    ["的", "de", "", ""],
    ["诗", "shī", "poem", "puisi"],
    ["，", "", "", ""],
    ["还是", "hái shì", "or", "atau"],
    ["做", "zuò", "be", "menjadi"],
    ["一只", "yī zhī", "a", "seekor"],
    ["蝶", "dié", "butterfly", "rama-rama"],
    ["的", "de", "", ""],
    ["画", "huà", "painting", "lukisan"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["风中", "fēng zhōng", "in the wind", "dalam angin"],
    ["奔跑", "bēn pǎo", "run", "berlari"],
    ["的", "de", "", ""],
    ["翩翩", "piān piān", "elegantly", "dengan anggun"],
    ["少年", "shào nián", "youth", "remaja"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["是", "shì", "are", "ialah"],
    ["想", "xiǎng", "want", "mahu"],
    ["做", "zuò", "be", "menjadi"],
    ["一只", "yī zhī", "a", "seekor"],
    ["鹰", "yīng", "eagle", "helang"],
    ["，", "", "", ""],
    ["与", "yǔ", "with", "dengan"],
    ["天", "tiān", "sky", "langit"],
    ["比高", "bǐ gāo", "compete in height", "banding tinggi"],
    ["？", "", "", ""],
    ["还是", "hái shì", "or", "atau"],
    ["做", "zuò", "be", "menjadi"],
    ["一条", "yī tiáo", "a", "sebatang"],
    ["壮阔", "zhuàng kuò", "grand", "megah"],
    ["的", "de", "", ""],
    ["长河", "cháng hé", "long river", "sungai panjang"],
    ["，", "", "", ""],
    ["为", "wèi", "for", "untuk"],
    ["大地", "dà dì", "earth", "bumi"],
    ["抒怀", "shū huái", "express feelings", "meluahkan perasaan"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["我", "wǒ", "I", "saya"],
    ["喜欢", "xǐ huān", "like", "suka"],
    ["做梦", "zuò mèng", "dream", "bermimpi"],
    ["。", "", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["让", "ràng", "let", "membuat"],
    ["我", "wǒ", "me", "saya"],
    ["看到", "kàn dào", "see", "melihat"],
    ["窗外", "chuāng wài", "outside window", "di luar tingkap"],
    ["的", "de", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["，", "", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["让", "ràng", "let", "membuat"],
    ["我", "wǒ", "me", "saya"],
    ["看到", "kàn dào", "see", "melihat"],
    ["天边", "tiān biān", "horizon", "ufuk"],
    ["的", "de", "", ""],
    ["彩霞", "cǎi xiá", "colorful clouds", "awan berwarna"],
    ["；", "", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["给", "gěi", "give", "memberi"],
    ["我", "wǒ", "me", "saya"],
    ["不变", "bù biàn", "unchanging", "tetap"],
    ["的", "de", "", ""],
    ["召唤", "zhào huàn", "call", "panggilan"],
    ["与", "yǔ", "and", "dan"],
    ["步伐", "bù fá", "pace", "langkah"],
    ["，", "", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["引", "yǐn", "lead", "memimpin"],
    ["我", "wǒ", "me", "saya"],
    ["去", "qù", "go", "pergi"],
    ["追逐", "zhuī zhú", "chase", "mengejar"],
    ["一个", "yī gè", "a", "sebuah"],
    ["又", "yòu", "again", "lagi"],
    ["一个", "yī gè", "a", "sebuah"],
    ["的", "de", "", ""],
    ["目标", "mù biāo", "goal", "matlamat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["1952年", "yī jiǔ wǔ èr nián", "year 1952", "tahun 1952"],
    ["，", "", "", ""],
    ["一个", "yī gè", "a", "seorang"],
    ["叫", "jiào", "called", "bernama"],
    ["查克·贝瑞", "chá kè · bèi ruì", "Chuck Berry", "Chuck Berry"],
    ["的", "de", "", ""],
    ["美国", "měi guó", "American", "Amerika"],
    ["青年", "qīng nián", "youth", "pemuda"],
    ["，", "", "", ""],
    ["做", "zuò", "had", "membuat"],
    ["了", "le", "", ""],
    ["这么", "zhè me", "such", "begitu"],
    ["一个", "yī gè", "a", "sebuah"],
    ["梦", "mèng", "dream", "impian"],
    ["：", "", "", ""],
    ["超越", "chāo yuè", "surpass", "melepasi"],
    ["贝多芬", "bèi duō fēn", "Beethoven", "Beethoven"],
    ["！", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["把", "bǎ", "", ""],
    ["这个", "zhè gè", "this", "ini"],
    ["消息", "xiāo xi", "news", "berita"],
    ["告诉", "gào su", "tell", "memberitahu"],
    ["柴科夫斯基", "chái kē fū sī jī", "Tchaikovsky", "Tchaikovsky"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["多年", "duō nián", "many years", "bertahun-tahun"],
    ["以后", "yǐ hòu", "later", "selepas"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["成功", "chéng gōng", "succeeded", "berjaya"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["成为", "chéng wéi", "become", "menjadi"],
    ["摇滚", "yáo gǔn", "rock", "rock"],
    ["音乐", "yīn yuè", "music", "muzik"],
    ["的", "de", "", ""],
    ["奠基人", "diàn jī rén", "founder", "pengasas"],
    ["之一", "zhī yī", "one of", "salah satu"],
    ["。", "", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["赋予", "fù yǔ", "endow", "memberi"],
    ["他", "tā", "him", "dia"],
    ["豪迈", "háo mài", "heroic", "berani"],
    ["的", "de", "", ""],
    ["宣言", "xuān yán", "declaration", "perisytiharan"],
    ["，", "", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["也", "yě", "also", "juga"],
    ["引领", "yǐn lǐng", "lead", "memimpin"],
    ["他", "tā", "him", "dia"],
    ["走向", "zǒu xiàng", "march towards", "menuju ke"],
    ["光明", "guāng míng", "bright", "cerah"],
    ["的", "de", "", ""],
    ["大道", "dà dào", "great path", "jalan besar"],
    ["。", "", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["启发", "qǐ fā", "inspire", "memberi ilham"],
    ["了", "le", "", ""],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["初心", "chū xīn", "original aspiration", "hasrat asal"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["则", "zé", "then", "maka"],
    ["用", "yòng", "use", "gunakan"],
    ["成功", "chéng gōng", "success", "kejayaan"],
    ["证明", "zhèng míng", "prove", "membuktikan"],
    ["了", "le", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["的", "de", "", ""],
    ["真实", "zhēn shí", "real", "benar"],
    ["与", "yǔ", "and", "dan"],
    ["壮美", "zhuàng měi", "magnificent", "agung"],
    ["——", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["有了", "yǒu le", "have", "mempunyai"],
    ["梦", "mèng", "dream", "impian"],
    ["，", "", "", ""],
    ["才", "cái", "then", "barulah"],
    ["有了", "yǒu le", "have", "mempunyai"],
    ["梦想", "mèng xiǎng", "dream", "impian"],
    ["；", "", "", ""],
    ["有了", "yǒu le", "have", "mempunyai"],
    ["梦想", "mèng xiǎng", "dream", "impian"],
    ["，", "", "", ""],
    ["才", "cái", "then", "barulah"],
    ["有了", "yǒu le", "have", "mempunyai"],
    ["理想", "lǐ xiǎng", "ideal", "cita-cita"],
    ["；", "", "", ""],
    ["有了", "yǒu le", "have", "mempunyai"],
    ["理想", "lǐ xiǎng", "ideal", "cita-cita"],
    ["，", "", "", ""],
    ["才", "cái", "then", "barulah"],
    ["有", "yǒu", "have", "ada"],
    ["为", "wèi", "for", "untuk"],
    ["理想", "lǐ xiǎng", "ideal", "cita-cita"],
    ["而", "ér", "and", "dan"],
    ["奋斗", "fèn dòu", "strive", "berjuang"],
    ["的", "de", "", ""],
    ["人生", "rén shēng", "life", "kehidupan"],
    ["历程", "lì chéng", "journey", "perjalanan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["没有", "méi yǒu", "without", "tanpa"],
    ["泪水", "lèi shuǐ", "tears", "air mata"],
    ["的", "de", "", ""],
    ["人", "rén", "person", "orang"],
    ["，", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["是", "shì", "is", "ialah"],
    ["干涸", "gān hé", "dry", "kering"],
    ["的", "de", "", ""],
    ["；", "", "", ""],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["梦", "mèng", "dream", "impian"],
    ["的", "de", "", ""],
    ["人", "rén", "person", "orang"],
    ["，", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["夜晚", "yè wǎn", "night", "malam"],
    ["是", "shì", "is", "ialah"],
    ["黑暗", "hēi àn", "dark", "gelap"],
    ["的", "de", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["太阳", "tài yáng", "sun", "matahari"],
    ["总", "zǒng", "always", "sentiasa"],
    ["在", "zài", "in", "di"],
    ["有", "yǒu", "have", "ada"],
    ["梦", "mèng", "dream", "impian"],
    ["的", "de", "", ""],
    ["地方", "dì fang", "place", "tempat"],
    ["升起", "shēng qǐ", "rise", "terbit"],
    ["；", "", "", ""],
    ["月亮", "yuè liang", "moon", "bulan"],
    ["也", "yě", "also", "juga"],
    ["总", "zǒng", "always", "sentiasa"],
    ["在", "zài", "in", "di"],
    ["有", "yǒu", "have", "ada"],
    ["梦", "mèng", "dream", "impian"],
    ["的", "de", "", ""],
    ["地方", "dì fang", "place", "tempat"],
    ["朦胧", "méng lóng", "hazy", "kabus"],
    ["。", "", "", ""],
    ["梦", "mèng", "dream", "impian"],
    ["是", "shì", "is", "ialah"],
    ["永恒", "yǒng héng", "eternal", "abadi"],
    ["的", "de", "", ""],
    ["微笑", "wēi xiào", "smile", "senyuman"],
    ["，", "", "", ""],
    ["使", "shǐ", "make", "membuat"],
    ["你的", "nǐ de", "your", "awak punya"],
    ["心灵", "xīn líng", "soul", "jiwa"],
    ["永远", "yǒng yuǎn", "forever", "selamanya"],
    ["充满", "chōng mǎn", "full of", "penuh dengan"],
    ["激情", "jī qíng", "passion", "semangat"],
    ["，", "", "", ""],
    ["使", "shǐ", "make", "membuat"],
    ["你的", "nǐ de", "your", "awak punya"],
    ["双眼", "shuāng yǎn", "eyes", "kedua-dua mata"],
    ["永远", "yǒng yuǎn", "forever", "selamanya"],
    ["澄澈", "chéng chè", "clear", "jernih"],
    ["明亮", "míng liàng", "bright", "terang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["世界", "shì jiè", "world", "dunia"],
    ["的", "de", "", ""],
    ["万花筒", "wàn huā tǒng", "kaleidoscope", "kaleidoskop"],
    ["散发", "sàn fā", "emit", "memancarkan"],
    ["着", "zhe", "", ""],
    ["诱人", "yòu rén", "tempting", "menarik"],
    ["的", "de", "", ""],
    ["清香", "qīng xiāng", "fragrance", "harum"],
    ["，", "", "", ""],
    ["未来", "wèi lái", "future", "masa depan"],
    ["的", "de", "", ""],
    ["天空", "tiān kōng", "sky", "langit"],
    ["下", "xià", "under", "bawah"],
    ["也", "yě", "also", "juga"],
    ["传来", "chuán lái", "come from", "datang"],
    ["迷人", "mí rén", "charming", "menawan"],
    ["的", "de", "", ""],
    ["歌唱", "gē chàng", "singing", "nyanyian"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["整装待发", "zhěng zhuāng dài fā", "ready to go", "bersedia untuk bertolak"],
    ["，", "", "", ""],
    ["用", "yòng", "use", "gunakan"],
    ["美梦", "měi mèng", "beautiful dream", "impian indah"],
    ["打扮", "dǎ bàn", "dress up", "berhias"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "daripada"],
    ["实干", "shí gàn", "work hard", "kerja keras"],
    ["开始", "kāi shǐ", "start", "bermula"],
    ["。", "", "", ""],
    ["等到", "děng dào", "wait until", "tunggu sehingga"],
    ["我们", "wǒ men", "we", "kita"],
    ["抵达", "dǐ dá", "arrive", "tiba di"],
    ["秋天", "qiū tiān", "autumn", "musim luruh"],
    ["的", "de", "", ""],
    ["果园", "guǒ yuán", "orchard", "kebun buah"],
    ["，", "", "", ""],
    ["轻轻", "qīng qīng", "gently", "perlahan"],
    ["地", "de", "", ""],
    ["擦去", "cā qù", "wipe away", "lap"],
    ["夏天", "xià tiān", "summer", "musim panas"],
    ["留在", "liú zài", "left on", "tertinggal di"],
    ["我们", "wǒ men", "our", "kita"],
    ["脸上", "liǎn shàng", "face", "muka"],
    ["的", "de", "", ""],
    ["汗水", "hàn shuǐ", "sweat", "peluh"],
    ["与", "yǔ", "and", "dan"],
    ["灰尘", "huī chén", "dust", "debu"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["就", "jiù", "then", "lalu"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["听得见", "tīng dé jiàn", "hear", "dengar"],
    ["曾经", "céng jīng", "once", "pernah"],
    ["对", "duì", "to", "kepada"],
    ["春天", "chūn tiān", "spring", "musim bunga"],
    ["说过", "shuō guò", "said", "berkata"],
    ["的", "de", "", ""],
    ["那", "nà", "that", "itu"],
    ["句话", "jù huà", "sentence", "ayat"],
    ["：", "", "", ""],
    ["美梦成真", "měi mèng chéng zhēn", "dream come true", "impian menjadi kenyataan"],
    ["！", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
